import Jacket from '../assets/2.jpg'
import Suit from '../assets/1.png'
import Jeans from '../assets/3.png'
import Gown from '../assets/4.jpg'
import Chic from '../assets/8.png'
import Floral from '../assets/6.jpg'
import Tshirt from '../assets/11.png'
import Jacket2 from '../assets/9.png'


export const ProductData = [
  {
      img: Jacket,
      category: "Men's Perfume",
      name: "Fresh Aqua",
      price: "$85.50",
  },
  {
      img: Suit,
      category: "Men's Perfume",
      name: "Elegant Noir",
      price: "$215.00",
  },
  {
      img: Gown,
      category: "Men's Perfume",
      name: "Woody Charm",
      price: "$45.99",
  },
  {
      img: Jeans,
      category: "Women's Perfume",
      name: "Floral Bloom",
      price: "$120.00",
  },
  {
      img: Floral,
      category: "Women's Perfume",
      name: "Chic Mist",
      price: "$32.25",
  },
  {
      img: Tshirt,
      category: "Women's Perfume",
      name: "Summer Breeze",
      price: "$40.00",
  },
  {
      img: Chic,
      category: "Men's Perfume",
      name: "Citrus Splash",
      price: "$25.00",
  },
  {
      img: Jacket2,
      category: "Women's Perfume",
      name: "Leather Essence",
      price: "$150.00",
  },
];




export const AllProductData = [
  {
      id: 1,
      img: Jacket2,
      category: "Men's Perfume",
      name: "Fresh Aqua",
      price: "$85.50",
  },
  {
      id: 2,
      img: Tshirt,
      category: "Men's Perfume",
      name: "Elegant Noir",
      price: "$215.00",
  },
  {
      id: 3,
      img: Floral,
      category: "Men's Perfume",
      name: "Woody Charm",
      price: "$45.99",
  },
  {
      id: 4,
      img: Chic,
      category: "Women's Perfume",
      name: "Floral Bloom",
      price: "$120.00",
  },
  {
      id: 5,
      img: Gown,
      category: "Women's Perfume",
      name: "Chic Mist",
      price: "$32.25",
  },
  {
      id: 6,
      img: Jeans,
      category: "Women's Perfume",
      name: "Summer Breeze",
      price: "$40.00",
  },
  {
      id: 7,
      img: Suit,
      category: "Men's Perfume",
      name: "Citrus Splash",
      price: "$25.00",
  },
  {
      id: 8,
      img: Jeans,
      category: "Women's Perfume",
      name: "Leather Essence",
      price: "$150.00",
  },
  {
      id: 9,
      img: Jeans,
      category: "Men's Perfume",
      name: "Bold Spice",
      price: "$85.50",
  },
  {
      id: 10,
      img: Jeans,
      category: "Unisex Perfume",
      name: "Ocean Breeze",
      price: "$45.00",
  },
  {
      id: 11,
      img: Jeans,
      category: "Men's Perfume",
      name: "Urban Musk",
      price: "$60.00",
  },
  {
      id: 12,
      img: Floral,
      category: "Unisex Perfume",
      name: "Sporty Notes",
      price: "$120.00",
  },
  {
      id: 13,
      img: Suit,
      category: "Women's Perfume",
      name: "Rose Petal",
      price: "$70.00",
  },
  {
      id: 14,
      img: Floral,
      category: "Accessories",
      name: "Perfume Travel Case",
      price: "$110.00",
  },
  {
      id: 15,
      img: Floral,
      category: "Accessories",
      name: "Scent Diffuser",
      price: "$25.00",
  },
  {
      id: 16,
      img: Floral,
      category: "Men's Perfume",
      name: "Mountain Mist",
      price: "$55.00",
  },
  {
      id: 17,
      img: Floral,
      category: "Unisex Perfume",
      name: "Amber Glow",
      price: "$140.00",
  },
  {
      id: 18,
      img: Floral,
      category: "Women's Perfume",
      name: "Night Rose",
      price: "$50.00",
  },
  {
      id: 19,
      img: Floral,
      category: "Accessories",
      name: "Perfume Organizer",
      price: "$150.00",
  },
  {
      id: 20,
      img: Floral,
      category: "Men's Perfume",
      name: "Elegant Woods",
      price: "$180.00",
  },
];


export const ProductInfo = [
  {
      id: 1,
      img: Gown,
      category: "Men's Perfume",
      name: "Fresh Aqua",
      price: "$85.50",
      description: "A refreshing aquatic fragrance with hints of citrus and ocean breeze, perfect for casual or professional settings.",
      sizes: ["50ml", "100ml", "150ml"],
      colors: ["Blue"],
      rating: 4.5,
      reviews: 120,
  },
  {
      id: 2,
      img: Gown,
      category: "Men's Perfume",
      name: "Elegant Noir",
      price: "$215.00",
      description: "A luxurious fragrance combining rich woody and musky notes for a bold, confident presence.",
      sizes: ["50ml", "100ml"],
      colors: ["Black"],
      rating: 4.8,
      reviews: 95,
  },
  {
      id: 3,
      img: Gown,
      category: "Men's Perfume",
      name: "Woody Charm",
      price: "$45.99",
      description: "An earthy blend of cedarwood and sandalwood with a hint of spice, ideal for everyday use.",
      sizes: ["30ml", "50ml", "100ml"],
      colors: ["Brown"],
      rating: 4.2,
      reviews: 250,
  },
  {
      id: 4,
      img: Gown,
      category: "Women's Perfume",
      name: "Floral Bloom",
      price: "$120.00",
      description: "A delicate mix of rose, jasmine, and lily of the valley, perfect for evening wear or romantic occasions.",
      sizes: ["50ml", "100ml"],
      colors: ["Pink"],
      rating: 5.0,
      reviews: 45,
  },
  {
      id: 5,
      img: Gown,
      category: "Women's Perfume",
      name: "Chic Mist",
      price: "$32.25",
      description: "A modern and elegant fragrance with fruity top notes and a floral heart, perfect for any occasion.",
      sizes: ["30ml", "50ml"],
      colors: ["White"],
      rating: 4.0,
      reviews: 100,
  },
  {
      id: 6,
      img: Gown,
      category: "Women's Perfume",
      name: "Summer Breeze",
      price: "$40.00",
      description: "A light and breezy fragrance with citrus and floral notes, ideal for warm sunny days.",
      sizes: ["30ml", "50ml", "100ml"],
      colors: ["Yellow"],
      rating: 4.3,
      reviews: 130,
  },
  {
      id: 7,
      img: Gown,
      category: "Men's Perfume",
      name: "Citrus Splash",
      price: "$25.00",
      description: "A vibrant fragrance with zesty citrus and herbal undertones, perfect for an energizing start to the day.",
      sizes: ["30ml", "50ml"],
      colors: ["Orange"],
      rating: 4.1,
      reviews: 150,
  },
  {
      id: 8,
      img: Gown,
      category: "Women's Perfume",
      name: "Leather Essence",
      price: "$150.00",
      description: "A bold blend of leather and amber with subtle floral hints, perfect for making a statement.",
      sizes: ["50ml", "100ml"],
      colors: ["Brown"],
      rating: 4.7,
      reviews: 200,
  },
  {
      id: 9,
      img: Gown,
      category: "Men's Perfume",
      name: "Bold Spice",
      price: "$85.50",
      description: "An intense blend of spices and smoky wood, ideal for evening outings.",
      sizes: ["50ml", "100ml"],
      colors: ["Red"],
      rating: 4.5,
      reviews: 180,
  },
  {
      id: 10,
      img: Gown,
      category: "Unisex Perfume",
      name: "Ocean Breeze",
      price: "$45.00",
      description: "A unisex fragrance with fresh marine notes and a hint of citrus, perfect for any occasion.",
      sizes: ["30ml", "50ml"],
      colors: ["Aqua"],
      rating: 4.6,
      reviews: 220,
  },
  {
      id: 11,
      img: Gown,
      category: "Men's Perfume",
      name: "Urban Musk",
      price: "$60.00",
      description: "A refined fragrance with musk and cedarwood for a sophisticated presence.",
      sizes: ["50ml", "100ml"],
      colors: ["Gray"],
      rating: 4.0,
      reviews: 110,
  },
  {
      id: 12,
      img: Gown,
      category: "Unisex Perfume",
      name: "Sporty Notes",
      price: "$120.00",
      description: "An energetic fragrance combining citrus, mint, and green notes, perfect for active lifestyles.",
      sizes: ["50ml", "100ml"],
      colors: ["Green"],
      rating: 4.3,
      reviews: 75,
  },
  {
      id: 13,
      img: Gown,
      category: "Women's Perfume",
      name: "Rose Petal",
      price: "$70.00",
      description: "A classic rose fragrance with subtle hints of vanilla, perfect for special occasions.",
      sizes: ["30ml", "50ml"],
      colors: ["Rose"],
      rating: 4.8,
      reviews: 50,
  },
  {
      id: 14,
      img: Gown,
      category: "Accessories",
      name: "Perfume Travel Case",
      price: "$110.00",
      description: "A stylish and protective travel case for carrying your favorite fragrances wherever you go.",
      sizes: ["One Size"],
      colors: ["Black", "Silver"],
      rating: 4.6,
      reviews: 180,
  },
  {
      id: 15,
      img: Gown,
      category: "Accessories",
      name: "Scent Diffuser",
      price: "$25.00",
      description: "A sleek and portable diffuser for filling your space with your favorite scents.",
      sizes: ["One Size"],
      colors: ["White"],
      rating: 4.4,
      reviews: 90,
  },
  {
      id: 16,
      img: Gown,
      category: "Men's Perfume",
      name: "Mountain Mist",
      price: "$55.00",
      description: "An invigorating fragrance with woody and earthy notes, inspired by nature.",
      sizes: ["30ml", "50ml"],
      colors: ["Green"],
      rating: 4.7,
      reviews: 200,
  },
  {
      id: 17,
      img: Gown,
      category: "Unisex Perfume",
      name: "Amber Glow",
      price: "$140.00",
      description: "A rich and luxurious blend of amber and vanilla, suitable for both men and women.",
      sizes: ["50ml", "100ml"],
      colors: ["Gold"],
      rating: 4.5,
      reviews: 130,
  },
  {
      id: 18,
      img: Gown,
      category: "Women's Perfume",
      name: "Night Rose",
      price: "$50.00",
      description: "A seductive fragrance with a mix of rose, patchouli, and amber, perfect for evening wear.",
      sizes: ["30ml", "50ml"],
      colors: ["Deep Red"],
      rating: 4.1,
      reviews: 160,
  },
  {
      id: 19,
      img: Gown,
      category: "Accessories",
      name: "Perfume Organizer",
      price: "$150.00",
      description: "An elegant organizer to store your perfume collection in style.",
      sizes: ["One Size"],
      colors: ["Black", "White"],
      rating: 4.9,
      reviews: 220,
  },
  {
      id: 20,
      img: Chic,
      category: "Men's Perfume",
      name: "Elegant Woods",
      price: "$180.00",
      description: "A warm and sophisticated fragrance with woody and smoky undertones.",
      sizes: ["50ml", "100ml"],
      colors: ["Brown"],
      rating: 4.7,
      reviews: 180,
  },
];

  